name: IDreamOfEasy
author: Bunnky
description: I Dream of Easy - Slimefun Legacy maintenance fork for modern Paper servers.
main: me.bunnky.idreamofeasy.IDreamOfEasy
website: https://github.com/wickidcow/IDreamOfEasy
version: ${project.version}
api-version: '1.21'
depend:
  - Slimefun
